def mutate_int(a: int) -> int: ...
def mutate_str(s: str) -> str: ...
def mutate_float(f: float) -> float: ...
def mutate_bytes(b: bytes) -> bytes: ...
def chain_rng_init(seed: int) -> None: ...
def chain_rng_rand_range(max: int) -> int: ...
def chain_rng_get_current_state() -> int: ...
