def mutate_int(a: int) -> int: ...
def mutate_str(s: str) -> str: ...
def mutate_float(f: float) -> float: ...
def mutate_bytes(b: bytes) -> bytes: ...
def set_random_state(seed: int) -> None: ...
def get_random_state() -> int: ...
def randint(max: int) -> int: ...
