#!/usr/bin/env python3
"""
Generate a coverage comparison table from *_seeds_cov.json and
*_seeds_sampled_cov.json files produced by count_seeds_running_loc.py.

Usage:
    uv run scripts/gen_coverage_table.py [-o experiments/RQ2/coverage_table.md]

Columns:
    TLOC        Total statements in measured files (from coverage JSON)
    SLOC        Lines covered by full seed set
    Sampled LOC Lines covered by sampled seed set
    DyFuzz LOC  (placeholder)
    Fuzz4All    (placeholder)
    Ours        (placeholder)
"""

import argparse
import json
import os
import sys
from pathlib import Path


def load_coverage(cov_path: Path) -> tuple[int, int]:
    """Return (tloc, covered) from a coverage JSON file."""
    if not cov_path.exists():
        return 0, 0
    with open(cov_path, encoding="utf-8") as f:
        data = json.load(f)
    files = data.get("files", {})
    tloc = sum(info.get("summary", {}).get("num_statements", 0) for info in files.values())
    covered = sum(len(info.get("executed_lines", [])) for info in files.values())
    return tloc, covered


def build_table(data_dir: Path, lib_order: list[str] | None = None) -> list[dict]:
    """
    Scan data_dir for *_seeds_cov.json and *_seeds_sampled_cov.json and
    return a list of dicts with coverage stats.
    """
    if lib_order is None:
        # Discover all library names from existing full-cov files
        lib_order = sorted({
            p.name.replace("_seeds_cov.json", "")
            for p in data_dir.glob("*_seeds_cov.json")
        })

    rows = []
    for lib in lib_order:
        full_cov = data_dir / f"{lib}_seeds_cov.json"
        samp_cov = data_dir / f"{lib}_seeds_sampled_cov.json"

        tloc, sloc = load_coverage(full_cov)
        _, sampled_loc = load_coverage(samp_cov)

        rows.append({
            "lib": lib,
            "tloc": tloc,
            "sloc": sloc,
            "sampled_loc": sampled_loc,
        })
    return rows


def render_markdown(rows: list[dict]) -> str:
    header = "| Library Name | TLOC   | SLOC   | Sampled LOC | DyFuzz LOC | Fuzz4All LOC | Ours LOC |"
    sep    = "|-------------|-------:|-------:|------------:|-----------:|-------------:|---------:|"
    lines  = [header, sep]
    for r in rows:
        pct = f"({r['sampled_loc']/r['tloc']*100:.1f}%)" if r["tloc"] else ""
        samp = f"{r['sampled_loc']:>6,} {pct}"
        lines.append(
            f"| {r['lib']:12s} | "
            f"{r['tloc']:>6,} | "
            f"{r['sloc']:>6,} | "
            f"{samp:>15} | - | - | - |"
        )
    return "\n".join(lines)


def render_console(rows: list[dict]) -> str:
    lines = []
    for r in rows:
        pct = f"{r['sampled_loc']/r['tloc']*100:.1f}%" if r["tloc"] else "N/A"
        lines.append(
            f"  {r['lib']:12s}  "
            f"TLOC={r['tloc']:>7,}  "
            f"SLOC={r['sloc']:>7,}  "
            f"Sampled={r['sampled_loc']:>7,} ({pct})"
        )
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description="Generate seed coverage comparison table.")
    parser.add_argument(
        "-d", "--data-dir",
        default=os.environ.get("RESPFUZZER_DATA_DIR", "RQ2_data_new_111"),
        help="Directory containing *_seeds_cov.json files (default: $RESPFUZZER_DATA_DIR or RQ2_data_new_111)",
    )
    parser.add_argument(
        "-o", "--output",
        help="Write markdown table to this file (default: print to stdout)",
    )
    parser.add_argument(
        "--lib",
        action="append",
        dest="libs",
        default=[],
        help="Library to include (can be repeated); by default all discovered libraries are included",
    )
    args = parser.parse_args()

    data_dir = Path(args.data_dir).expanduser().resolve()
    if not data_dir.is_dir():
        print(f"ERROR: not a directory: {data_dir}", file=sys.stderr)
        sys.exit(1)

    lib_order = args.libs if args.libs else None
    rows = build_table(data_dir, lib_order)

    if not rows:
        print("ERROR: no coverage files found", file=sys.stderr)
        sys.exit(1)

    table_md = render_markdown(rows)

    if args.output:
        out_path = Path(args.output)
        out_path.parent.mkdir(parents=True, exist_ok=True)
        description = (
            "## Column Descriptions\n"
            "\n"
            "- **TLOC**: Total statements in measured source files (theoretical maximum)\n"
            "- **SLOC**: Statements covered by running all seeds\n"
            "- **Sampled LOC**: Statements covered by running sampled seeds (percentage = sampled/TLOC)\n"
            "- **DyFuzz LOC**: Placeholder\n"
            "- **Fuzz4All LOC**: Placeholder\n"
            "- **Ours LOC**: Placeholder\n"
        )
        doc = (
            "# Seed Coverage Table\n\n"
            "Auto-generated by scripts/gen_coverage_table.py\n\n"
            f"{table_md}\n\n"
            f"{description}\n"
        )
        out_path.write_text(doc, encoding="utf-8")
        print(f"Written: {out_path}")
    else:
        print(render_console(rows))
        print()
        print(table_md)


if __name__ == "__main__":
    main()
