# List of libraries to process - keep this in sync with scripts/install_lut.sh
# The install script installs these packages via pip. Use the same names here.
# third_libraries=(

# )

# # 最初版本
third_libraries=(
        "nltk"
        "dask"
        "yaml" # PyYAML
        "prophet"
        "numpy"
        "pandas"
        "sklearn" # Scikit-learn
        "scipy"
        "requests"
        "spacy"
        "torch"
        "paddle" # PaddlePaddle
)

py_libraries=(

)

libraries=(
        "${third_libraries[@]}"
        "${py_libraries[@]}"
)