libraries=(
        "nltk"
        "dask"
        "yaml" # PyYAML
        "prophet"
        "numpy"
        "pandas"
        "sklearn" # Scikit-learn
        "scipy"
        "requests"
        "spacy"
        "torch"
        "paddle" # PaddlePaddle
)